### ISSUE TITLE
`::set-output` is deprecated.

### ISSUE THREAD

**Issue by fabiocaccamo** [saadmk11/github-action-utils#12]
Thank you for these utils! 

I see that `::set-output` is still used:
https://github.com/saadmk11/github-action-utils/blob/main/github_action_utils.py#L152

More info about the deprecation and the solution here:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://hynek.me/til/set-output-deprecation-github-actions/

If you fix this and publish a new release, I will be glad to start using this library!

**Comment by saadmk11** [comment]
Hi @fabiocaccamo Thank you for reporting this issue, I have released a new version with the changes for `set-output` and `save-state`. https://pypi.org/project/github-action-utils/

**Comment by fabiocaccamo** [comment]
@saadmk11 thank you very much for the quick fix and feedback!
